version: "3.1"
services:
  mongodb:
    container_name: mongodb
    restart: always
    image: mongo:latest
    command: mongod
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    networks:
      - app-network

  frontend:
    container_name: frontend
    restart: always
    image: rai-rub-jai-front:0.1
    ports:
      - 80:80
    networks:
      - app-network

  backend:
    image: rai-rub-jai:0.3
    restart: always
    container_name: backend
    depends_on:
      - mongodb
    ports:
      - 5001:5001
    env_file:
      - ./backend/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
