version: "3.1"
services:
  mongodb:
    container_name: mongodb
    restart: always
    image: mongo:latest
    command: mongod
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    networks:
      app-network:
        ipv4_address: 192.168.64.2

  frontend:
    container_name: frontend
    restart: always
    image: rai-rub-jai-front
    depends_on:
      - backend
    ports:
      - 80:80
    networks:
      app-network:
        ipv4_address: 192.168.64.4

  backend:
    image: rai-rub-jai
    restart: always
    container_name: backend
    depends_on:
      - mongodb
    ports:
      - 5001:5001
    env_file:
      - ./backend/.env
    networks:
      app-network:
        ipv4_address: 192.168.64.3

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.64.0/16
          gateway: 192.168.64.1
